# Generated by Django 5.1 on 2024-08-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'お問い合わせ'},
        ),
        migrations.AlterModelTable(
            name='inquiry',
            table='contact',
        ),
    ]
