# Generated by Django 5.1 on 2024-08-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='sample@example.com', max_length=255, unique=True, verbose_name='メールアドレス'),
        ),
    ]
