# Generated by Django 5.1 on 2024-08-30 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='難易度')),
            ],
            options={
                'verbose_name_plural': '難易度',
                'db_table': 'level',
            },
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='品詞')),
            ],
            options={
                'verbose_name_plural': '品詞',
                'db_table': 'part_of_speech',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=255, verbose_name='英語')),
                ('japanese', models.CharField(max_length=255, verbose_name='日本語')),
                ('phrase', models.TextField(blank=True, null=True, verbose_name='成句')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.level', verbose_name='難易度')),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.partofspeech', verbose_name='品詞')),
            ],
            options={
                'verbose_name_plural': '単語',
                'db_table': 'word',
            },
        ),
    ]
