# Generated by Django 5.1 on 2024-08-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=255, verbose_name='英語')),
                ('japanese', models.CharField(max_length=255, verbose_name='日本語')),
                ('part_of_speech', models.CharField(choices=[('名詞', '名詞'), ('形容詞', '形容詞'), ('代名詞', '代名詞'), ('副詞', '副詞'), ('動詞', '動詞'), ('自動詞', '自動詞'), ('他動詞', '他動詞'), ('自動詞・他動詞', '自動詞、他動詞'), ('助動詞', '助動詞'), ('前置詞', '前置詞'), ('接続詞', '接続詞'), ('間投詞', '間投詞')], max_length=50, verbose_name='品詞')),
                ('phrase', models.TextField(blank=True, null=True, verbose_name='成句')),
                ('level', models.CharField(choices=[('Beginner', '初級(中学)'), ('Intermediate', '中級(高校)'), ('Advanced', '上級(大学,社会人)'), ('Expert', '特級(それ以上)')], max_length=20, null=True, verbose_name='難易度')),
            ],
            options={
                'verbose_name_plural': '単語',
                'db_table': 'word',
            },
        ),
    ]
