# Generated by Django 5.1 on 2024-08-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='説明'),
        ),
    ]
