# Generated by Django 5.1 on 2024-08-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_searchhistory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=255)),
                ('japanese', models.CharField(max_length=255)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('phrase', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
