# Generated by Django 5.1 on 2024-08-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_word_delete_searchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name_plural': '単語'},
        ),
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.CharField(choices=[('Beginner', '初級(中学)'), ('Intermediate', '中級(高校)'), ('Advanced', '上級(大学,社会人)'), ('Expert', '特級(それ以上)')], max_length=20, null=True, verbose_name='難易度'),
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=255, verbose_name='英語'),
        ),
        migrations.AlterField(
            model_name='word',
            name='japanese',
            field=models.CharField(max_length=255, verbose_name='日本語'),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('名', '名詞'), ('形', '形容詞'), ('代', '代名詞'), ('副', '副詞'), ('動', '動詞'), ('自', '自動詞'), ('他', '他動詞'), ('自他', '自動詞、他動詞'), ('助', '助動詞'), ('前', '前置詞'), ('接', '接続詞'), ('間', '間投詞')], max_length=50, verbose_name='品詞'),
        ),
        migrations.AlterField(
            model_name='word',
            name='phrase',
            field=models.TextField(blank=True, null=True, verbose_name='成句'),
        ),
        migrations.AlterModelTable(
            name='word',
            table='word',
        ),
    ]
